$ErrorActionPreference = "Stop"

$Root = "D:\DevProject\PythonProject\VATranscribeWeb"

if (-not (Test-Path $Root)) {
    throw "Project root not found: $Root"
}

Set-Location $Root

Write-Host "Creating VATranscribeWeb base structure..."

$Dirs = @(
    "apps/marketing/src/pages",
    "apps/marketing/src/components",
    "apps/marketing/src/layouts",
    "apps/marketing/src/content",
    "apps/marketing/src/config",
    "apps/marketing/src/styles",
    "apps/marketing/public",

    "apps/web/src/app",
    "apps/web/src/pages",
    "apps/web/src/features",
    "apps/web/src/entities",
    "apps/web/src/widgets",
    "apps/web/src/shared",

    "apps/admin/src/app",
    "apps/admin/src/pages",
    "apps/admin/src/features",
    "apps/admin/src/entities",
    "apps/admin/src/widgets",
    "apps/admin/src/shared",

    "apps/api/app/api/v1/endpoints",
    "apps/api/app/core",
    "apps/api/app/models",
    "apps/api/app/schemas",
    "apps/api/app/services",
    "apps/api/app/providers/payments",
    "apps/api/app/providers/fiscalization",
    "apps/api/app/providers/ads",
    "apps/api/app/providers/affiliate",
    "apps/api/app/providers/storage",
    "apps/api/app/providers/email",
    "apps/api/app/dependencies",
    "apps/api/app/middleware",
    "apps/api/app/security",
    "apps/api/tests",

    "apps/worker/app/tasks/downloads",
    "apps/worker/app/tasks/transcriptions",
    "apps/worker/app/tasks/exports",
    "apps/worker/app/tasks/billing",
    "apps/worker/app/tasks/fiscal",
    "apps/worker/app/tasks/affiliate",
    "apps/worker/app/tasks/ads",
    "apps/worker/app/tasks/email",
    "apps/worker/app/tasks/cleanup",
    "apps/worker/app/boot",
    "apps/worker/tests",

    "apps/desktop/src",
    "apps/desktop/src-tauri/src",
    "apps/desktop/desktop-backend",

    "packages/core/vatranscribe_core/domain",
    "packages/core/vatranscribe_core/config",
    "packages/core/vatranscribe_core/utils",
    "packages/core/vatranscribe_core/monetization",
    "packages/shared-types/src",
    "packages/sdk/src",

    "infra/docker",
    "infra/nginx/sites",
    "infra/compose",
    "infra/db",
    "infra/scripts",
    "infra/deploy",
    "infra/security",
    "infra/backup",

    "alembic/versions",

    "docs/architecture",
    "docs/api",
    "docs/billing",
    "docs/monetization",
    "docs/security",
    "docs/privacy",
    "docs/legal",
    "docs/desktop",
    "docs/deployment",
    "docs/roadmap",

    "scripts/dev",
    "scripts/migrations",
    "scripts/maintenance",
    "scripts/packaging",
    "scripts/reports",
    "scripts/security",
    "scripts/backup",

    "tests/api",
    "tests/worker",
    "tests/billing",
    "tests/monetization",
    "tests/security",
    "tests/privacy",
    "tests/compliance",
    "tests/integration",
    "tests/fixtures",

    ".github/workflows"
)

foreach ($Dir in $Dirs) {
    New-Item -ItemType Directory -Force -Path $Dir | Out-Null
    New-Item -ItemType File -Force -Path (Join-Path $Dir ".gitkeep") | Out-Null
}

$ReadmeLines = @(
    "# VATranscribeWeb",
    "",
    "Commercial SaaS/Web repository for VATranscribe.",
    "",
    "## Purpose",
    "",
    "- marketing landing and SEO site",
    "- user web app",
    "- admin panel",
    "- FastAPI backend",
    "- Celery worker",
    "- desktop app shell",
    "- billing, subscriptions, payments, fiscal receipts",
    "- usage quotas and credits",
    "- licenses and devices",
    "- affiliate, ads and sponsored placements",
    "- security, privacy and compliance foundation",
    "",
    "## Main apps",
    "",
    "apps/marketing - public landing, SEO, docs, blog, legal pages",
    "apps/web - user dashboard and SaaS application",
    "apps/admin - internal admin panel",
    "apps/api - FastAPI backend",
    "apps/worker - Celery background workers",
    "apps/desktop - desktop application shell",
    "",
    "## Roadmap",
    "",
    "See docs/roadmap/implementation-stages.md"
)
Set-Content -Encoding UTF8 -Path "README.md" -Value $ReadmeLines

$GitignoreLines = @(
    "# OS / IDE",
    ".DS_Store",
    "Thumbs.db",
    ".idea/",
    ".vscode/",
    "",
    "# Python",
    "__pycache__/",
    "*.py[cod]",
    "*.pyo",
    "*.pyd",
    "*.egg-info/",
    ".pytest_cache/",
    ".mypy_cache/",
    ".ruff_cache/",
    ".coverage",
    "htmlcov/",
    "dist/",
    "build/",
    "",
    "# Virtual environments",
    ".venv/",
    "venv/",
    "env/",
    "",
    "# Node",
    "node_modules/",
    "npm-debug.log*",
    "yarn-debug.log*",
    "yarn-error.log*",
    ".pnpm-store/",
    ".next/",
    ".nuxt/",
    ".turbo/",
    ".parcel-cache/",
    "coverage/",
    "",
    "# Environment",
    ".env",
    ".env.*",
    "!.env.example",
    "",
    "# Runtime data",
    "storage/",
    "data/",
    "tmp/",
    "temp/",
    ".cache/",
    "logs/",
    "*.log",
    "",
    "# Media / generated files",
    "*.mp4",
    "*.mp3",
    "*.wav",
    "*.mkv",
    "*.avi",
    "*.mov",
    "*.webm",
    "*.srt",
    "*.vtt",
    "",
    "# Databases",
    "*.sqlite",
    "*.sqlite3",
    "*.db",
    "",
    "# Archives",
    "*.zip",
    "*.rar",
    "*.7z",
    "*.tar",
    "*.gz",
    "",
    "# Docker volumes",
    "docker-data/",
    "docker-volumes/",
    "pgdata/",
    "redis-data/"
)
Set-Content -Encoding UTF8 -Path ".gitignore" -Value $GitignoreLines

$DockerignoreLines = @(
    ".git",
    ".gitignore",
    ".github",
    ".idea",
    ".vscode",
    "node_modules",
    ".venv",
    "venv",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "storage",
    "data",
    "tmp",
    "temp",
    "logs",
    "*.log",
    "*.zip",
    "*.rar",
    "*.7z",
    "*.tar",
    "*.gz",
    ".env",
    ".env.*",
    "!.env.example",
    "dist",
    "build",
    "coverage",
    "htmlcov"
)
Set-Content -Encoding UTF8 -Path ".dockerignore" -Value $DockerignoreLines

$EnvLines = @(
    "# App",
    "APP_ENV=local",
    "APP_NAME=VATranscribeWeb",
    "APP_BASE_URL=http://localhost:5173",
    "ADMIN_BASE_URL=http://localhost:5174",
    "MARKETING_BASE_URL=http://localhost:4321",
    "API_BASE_URL=http://localhost:8000",
    "",
    "# Database",
    "DATABASE_URL=postgresql+psycopg://postgres:postgres@localhost:5432/vatranscribe_web",
    "",
    "# Redis / Celery",
    "REDIS_URL=redis://localhost:6379/0",
    "CELERY_BROKER_URL=redis://localhost:6379/0",
    "CELERY_RESULT_BACKEND=redis://localhost:6379/1",
    "",
    "# Auth",
    "JWT_SECRET_KEY=change-me",
    "JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30",
    "JWT_REFRESH_TOKEN_EXPIRE_DAYS=30",
    "",
    "# Security",
    "CORS_ALLOWED_ORIGINS=http://localhost:4321,http://localhost:5173,http://localhost:5174",
    "RATE_LIMIT_ENABLED=true",
    "",
    "# Billing",
    "BILLING_PROVIDER=mock",
    "DEFAULT_FREE_PLAN_CODE=free",
    "TRIAL_ENABLED=true",
    "TRIAL_DAYS=7",
    "",
    "# YooKassa",
    "YOOKASSA_SHOP_ID=",
    "YOOKASSA_SECRET_KEY=",
    "YOOKASSA_RETURN_URL=",
    "YOOKASSA_WEBHOOK_SECRET=",
    "",
    "# CloudPayments",
    "CLOUDPAYMENTS_PUBLIC_ID=",
    "CLOUDPAYMENTS_API_SECRET=",
    "",
    "# T-Bank",
    "TBANK_TERMINAL_KEY=",
    "TBANK_PASSWORD=",
    "TBANK_WEBHOOK_SECRET=",
    "",
    "# Fiscalization",
    "FISCALIZATION_PROVIDER=mock",
    "FISCAL_RECEIPTS_ENABLED=false",
    "",
    "# Ads / Affiliate",
    "ADS_ENABLED=false",
    "YANDEX_RSY_PARTNER_ID=",
    "YANDEX_RSY_SITE_ID=",
    "AFFILIATE_ENABLED=true",
    "",
    "# Email",
    "EMAIL_PROVIDER=mock",
    "SMTP_HOST=",
    "SMTP_PORT=",
    "SMTP_USER=",
    "SMTP_PASSWORD=",
    "EMAIL_FROM=noreply@example.com",
    "",
    "# Storage",
    "STORAGE_DRIVER=local",
    "STORAGE_ROOT=storage",
    "PUBLIC_STORAGE_BASE_URL=http://localhost:8000/storage"
)
Set-Content -Encoding UTF8 -Path ".env.example" -Value $EnvLines

$PackageJsonLines = @(
    "{",
    '  "name": "vatranscribe-web",',
    '  "private": true,',
    '  "version": "0.1.0",',
    '  "description": "Commercial SaaS/Web monorepo for VATranscribe.",',
    '  "workspaces": [',
    '    "apps/marketing",',
    '    "apps/web",',
    '    "apps/admin",',
    '    "apps/desktop",',
    '    "packages/shared-types",',
    '    "packages/sdk"',
    "  ],",
    '  "scripts": {',
    '    "dev": "turbo run dev",',
    '    "build": "turbo run build",',
    '    "lint": "turbo run lint",',
    '    "test": "turbo run test",',
    '    "dev:marketing": "npm run dev --workspace apps/marketing",',
    '    "dev:web": "npm run dev --workspace apps/web",',
    '    "dev:admin": "npm run dev --workspace apps/admin",',
    '    "dev:desktop": "npm run dev --workspace apps/desktop"',
    "  },",
    '  "devDependencies": {',
    '    "turbo": "^2.5.0"',
    "  }",
    "}"
)
Set-Content -Encoding UTF8 -Path "package.json" -Value $PackageJsonLines

$TurboLines = @(
    "{",
    '  "$schema": "https://turbo.build/schema.json",',
    '  "tasks": {',
    '    "dev": {',
    '      "cache": false,',
    '      "persistent": true',
    "    },",
    '    "build": {',
    '      "dependsOn": ["^build"],',
    '      "outputs": ["dist/**", ".astro/**", ".next/**"]',
    "    },",
    '    "lint": {',
    '      "dependsOn": ["^lint"]',
    "    },",
    '    "test": {',
    '      "dependsOn": ["^test"]',
    "    }",
    "  }",
    "}"
)
Set-Content -Encoding UTF8 -Path "turbo.json" -Value $TurboLines

$PyprojectLines = @(
    "[project]",
    'name = "vatranscribe-web"',
    'version = "0.1.0"',
    'description = "Commercial SaaS/Web backend and core packages for VATranscribe."',
    'requires-python = ">=3.11"',
    "dependencies = []",
    "",
    "[tool.pytest.ini_options]",
    "testpaths = [",
    '    "tests",',
    '    "apps/api/tests",',
    '    "apps/worker/tests"',
    "]",
    "pythonpath = [",
    '    ".",',
    '    "apps/api",',
    '    "apps/worker",',
    '    "packages/core"',
    "]",
    "",
    "[tool.ruff]",
    "line-length = 100",
    'target-version = "py311"',
    "",
    "[tool.ruff.lint]",
    'select = ["E", "F", "I", "UP", "B"]',
    "ignore = []"
)
Set-Content -Encoding UTF8 -Path "pyproject.toml" -Value $PyprojectLines

$AlembicLines = @(
    "[alembic]",
    "script_location = alembic",
    "prepend_sys_path = .",
    "version_path_separator = os",
    "",
    "sqlalchemy.url = driver://user:pass@localhost/dbname",
    "",
    "[loggers]",
    "keys = root,sqlalchemy,alembic",
    "",
    "[handlers]",
    "keys = console",
    "",
    "[formatters]",
    "keys = generic",
    "",
    "[logger_root]",
    "level = WARN",
    "handlers = console",
    "qualname =",
    "",
    "[logger_sqlalchemy]",
    "level = WARN",
    "handlers =",
    "qualname = sqlalchemy.engine",
    "",
    "[logger_alembic]",
    "level = INFO",
    "handlers =",
    "qualname = alembic",
    "",
    "[handler_console]",
    "class = StreamHandler",
    "args = (sys.stderr,)",
    "level = NOTSET",
    "formatter = generic",
    "",
    "[formatter_generic]",
    "format = %(levelname)-5.5s [%(name)s] %(message)s",
    "datefmt = %H:%M:%S"
)
Set-Content -Encoding UTF8 -Path "alembic.ini" -Value $AlembicLines

$MakefileLines = @(
    ".PHONY: help dev build test lint",
    "",
    "help:",
    "`t@echo `"VATranscribeWeb commands`"",
    "`t@echo `"  make dev      - run monorepo dev tasks`"",
    "`t@echo `"  make build    - build all apps`"",
    "`t@echo `"  make test     - run tests`"",
    "`t@echo `"  make lint     - run linters`"",
    "",
    "dev:",
    "`tnpm run dev",
    "",
    "build:",
    "`tnpm run build",
    "",
    "test:",
    "`tnpm run test",
    "",
    "lint:",
    "`tnpm run lint"
)
Set-Content -Encoding UTF8 -Path "Makefile" -Value $MakefileLines

$RoadmapLines = @(
    "# Implementation Stages",
    "",
    "## Stage 0 - Repository Foundation",
    "- create final monorepo structure",
    "- migrate existing VATranscribe_clean modules",
    "- keep old implementations safe",
    "- prepare docs, env and CI placeholders",
    "",
    "## Stage 1 - Security and Privacy Foundation",
    "- auth hardening",
    "- refresh token rotation",
    "- user consents",
    "- audit logs",
    "- file ownership checks",
    "- rate limits",
    "- privacy requests",
    "",
    "## Stage 2 - SaaS Billing",
    "- plans",
    "- subscriptions",
    "- payments",
    "- webhooks",
    "- fiscal receipts",
    "",
    "## Stage 3 - Usage, Quota and Credits",
    "- usage events",
    "- quota reservations",
    "- credit packs",
    "- monthly limits",
    "",
    "## Stage 4 - Desktop Licensing",
    "- licenses",
    "- devices",
    "- activations",
    "- desktop release downloads",
    "",
    "## Stage 5 - Marketing, SEO and Monetization",
    "- marketing site",
    "- SEO pages",
    "- affiliate links",
    "- ads",
    "- sponsored placements"
)
Set-Content -Encoding UTF8 -Path "docs/roadmap/implementation-stages.md" -Value $RoadmapLines

$StructureDocLines = @(
    "# Project Structure",
    "",
    "Target VATranscribeWeb monorepo structure.",
    "",
    "apps/marketing - public landing, SEO, blog, docs and legal pages",
    "apps/web - user SaaS application",
    "apps/admin - internal admin panel",
    "apps/api - FastAPI backend",
    "apps/worker - Celery workers",
    "apps/desktop - desktop app shell",
    "",
    "packages/core - shared media processing core",
    "packages/shared-types - shared TypeScript contracts",
    "packages/sdk - future API SDK",
    "",
    "infra - Docker, Nginx, compose, deploy and backup configuration",
    "docs - architecture, security, privacy, billing and roadmap documentation",
    "scripts - developer, migration, report and maintenance scripts",
    "tests - API, worker, billing, security, privacy and integration tests"
)
Set-Content -Encoding UTF8 -Path "docs/architecture/project-structure.md" -Value $StructureDocLines

Set-Content -Encoding UTF8 -Path "packages/core/vatranscribe_core/__init__.py" -Value '"""VATranscribe core package."""'
Set-Content -Encoding UTF8 -Path "apps/api/app/__init__.py" -Value '"""FastAPI application package."""'
Set-Content -Encoding UTF8 -Path "apps/worker/app/__init__.py" -Value '"""Celery worker package."""'

Write-Host ""
Write-Host "Base structure created successfully."
Write-Host ""
Write-Host "Next commands:"
Write-Host "git status"
Write-Host "git add ."
Write-Host 'git commit -m "chore: initialize VATranscribeWeb SaaS monorepo structure"'