.PHONY: help dev build test lint

help:
	@echo "VATranscribeWeb commands"
	@echo "  make dev      - run monorepo dev tasks"
	@echo "  make build    - build all apps"
	@echo "  make test     - run tests"
	@echo "  make lint     - run linters"

dev:
	npm run dev

build:
	npm run build

test:
	npm run test

lint:
	npm run lint
